disabled_rules:
  - line_length

opt_in_rules:
  - force_unwrapping
  - vertical_whitespace
  - closure_spacing
  - closure_end_indentation
  - explicit_init
  - switch_case_on_newline
  - redundant_nil_coalescing
  - prohibited_super_call
  - overridden_super_call
  - nimble_operator

file_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 500
  error: 1200

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

identifier_name:
  excluded:
    - id
    - up

excluded:
  - Pods
